var template_content;
var csv_file_content;
var child_prompt_1;
var child_prompt_2;
var user = false;
var count = 0;
var file_content;
var isSequential = false;
var public = true;
var pID;
var prompt_no = 0;
var template;
var user_prompts;
var price;
var teaser = ''
var title = ''
var max_char_title = 150;
var max_char_teaser = 250;
var author;
var url;
var subtopic;
var method;
var PD;
var hint;
var topic;
var tone;
var prompt_selected;
var extra_parent_prompts;
var childPrompt;
var maxlength = 10;
var chat_bot_response = '';